from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(1140, 700)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"background-color: rgb(100, 185, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(770, 0, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color: rgb(100, 185, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.img1 = QtWidgets.QLabel(self.frame)
        self.img1.setGeometry(QtCore.QRect(0, 30, 761, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.img1.setFont(font)
        self.img1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img1.setText("")
        self.img1.setObjectName("img1")
        self.img2 = QtWidgets.QLabel(self.frame)
        self.img2.setGeometry(QtCore.QRect(770, 30, 371, 221))
        self.img2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img2.setText("")
        self.img2.setScaledContents(True)
        self.img2.setObjectName("img2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(770, 270, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;\n"
"background-color: rgb(100, 185, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.statusFrame = QtWidgets.QFrame(self.frame)
        self.statusFrame.setGeometry(QtCore.QRect(770, 300, 371, 191))
        self.statusFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.label_6 = QtWidgets.QLabel(self.statusFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.statusFrame)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.statusFrame)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lbl_accuracy = QtWidgets.QLabel(self.statusFrame)
        self.lbl_accuracy.setGeometry(QtCore.QRect(290, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_accuracy.setFont(font)
        self.lbl_accuracy.setStyleSheet("color:white;")
        self.lbl_accuracy.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_accuracy.setObjectName("lbl_accuracy")
        self.lbl_char = QtWidgets.QLabel(self.statusFrame)
        self.lbl_char.setGeometry(QtCore.QRect(290, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Siyam Rupali ANSI")
        font.setPointSize(18)
        self.lbl_char.setFont(font)
        self.lbl_char.setStyleSheet("color:white;")
        self.lbl_char.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_char.setObjectName("lbl_char")
        self.lbl_count = QtWidgets.QLabel(self.statusFrame)
        self.lbl_count.setGeometry(QtCore.QRect(290, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_count.setFont(font)
        self.lbl_count.setStyleSheet("color:white;")
        self.lbl_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_count.setObjectName("lbl_count")
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"font: 32pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color:white;\n"
"font: 32pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 85, 127);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/training_80px.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Live Camera"))
        self.label_4.setText(_translate("Form", "Mimic Sign"))
        self.label_5.setText(_translate("Form", "Learning Status"))
        self.label_6.setText(_translate("Form", "Recognition Accuracy : "))
        self.label_7.setText(_translate("Form", "Character :"))
        self.label_8.setText(_translate("Form", "Learning Count :"))
        self.lbl_accuracy.setText(_translate("Form", "100%"))
        self.lbl_char.setText(_translate("Form", "ক"))
        self.lbl_count.setText(_translate("Form", "0/49"))
        self.label.setText(_translate("Form", "BSL Smart Avator Tutor\n"
""))

import res

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

